FROM alpine:latest

WORKDIR /app 

# Installs gcc
RUN apk add --no-cache build-base util-linux-dev mpc1-dev

COPY . /app
RUN ls /usr/lib
RUN gcc -luuid -o myapp main.c

EXPOSE 8080

ENTRYPOINT ["./myapp"]
