FROM alpine:3.21.3

WORKDIR /app 

# Installs gcc
RUN apk add --no-cache build-base && \
# Installs curl
    apk add --no-cache curl

COPY . /app

RUN gcc -o myapp main.c

EXPOSE 8080

ENTRYPOINT ["./myapp"]
